@startuml
hide footbox
skinparam sequenceMessageAlign center
skinparam lifelineStrategy solid
skinparam SequenceLifeLineBorderColor grey
skinparam SequenceLifeLineBorderThickness 1
skinparam ParticipantPadding 30
skinparam BoxPadding 10
skinparam SequenceBoxBackgroundColor white
skinparam SequenceGroupBackgroundColor white
skinparam SequenceMessageAlignment center
!define ACTOR_STYLE stereotype actor
!define BOUNDARY_STYLE stereotype boundary
!define CONTROL_STYLE stereotype control
!define DATABASE_STYLE stereotype database
skinparam backgroundColor white
skinparam title {
  FontSize 20
  FontStyle bold
}
title Biểu đồ trình tự cho chức năng "Đăng nhập" 
actor "Độc Giả" as KH
participant "Đăng nhập\n(Controller)" as C
participant "Đăng nhập\n(View)" as V
participant "UserModel\n(Model)" as M 
participant "CSDL\n(Database)" as DB 
KH ->> C: 1: Truy cập URL đăng nhập
activate C
C ->> V: 2: Khởi tạo và trả về View đăng nhập
activate V
V -->> KH: 3: Yêu cầu nhập thông tin đăng nhập
deactivate V
KH ->> C: 4: Nhập tên đăng nhập, mật khẩu và submit
C ->> C: 5: Kiểm tra dữ liệu đầu vào
activate C #DarkSalmon
deactivate C
C ->> M: 6: Yêu cầu xác thực đăng nhập
activate M
M ->> DB: 7: Truy vấn thông tin người dùng
activate DB
DB -->> M: 8: Trả về kết quả xác thực
deactivate DB
M -->> C: 9: Trả về kết quả xác thực
deactivate M
C -->> KH: 10: Trả về kết quả đăng nhập
deactivate C
@enduml